version: "3.10"

services:
  pyspark:
  #image: jupyter/pyspark-notebook:spark-3.3.1
    container_name: 'pyspark_container'
    image: 'pyspark_image'
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build: .
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - "8888:8888"
    volumes:
      - ./pyspark:/work
    command: start-notebook.sh --NotebookApp.token=''
